cmake:

  # global variables for ruslo/hunter (hint: set HunterGate cache)
  hunter:

    gate:
      url: "https://github.com/ruslo/hunter/archive/v0.19.71.tar.gz"
      sha1: "8fe144d9490501d398777532e0c0f56bc7bb0ec7"
      filepath: "${CMAKE_CURRENT_LIST_DIR}/cmake/Hunter/config.cmake"

  