sudo: required

services:
  - docker

before_install:
  - sudo docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - echo "success"

notifications:
  slack:
    secure: zEMULZVPN1T/KVxWJtOKVZ1aRrtz3d1eZx4n2qoHsNYJDG3XEviPxKtplTWLTzAzHQJ51Xf+hLl079YM2QaEZXrmZVw03IXgAc1qcKd3qep409d5moLuB46ybTBQgDWyHdCP3YP0N56FnJNifAxbJTaP5tZ7yrwB35BfqJjzae+LL0/a8Ksm/Y4uClbJ/MHLVlXzweSk0u0bM5wv56wVnOfHhGaqZ4AHlD+akZ7a5FvhzyY7GjrLIwM+CJppb6L5wOmC/OklUoZw4B4MBDBkP1zjEylmVNysXCqpdEXRr01d2IjE0EzWcP2F95GSKxZHxXlcBp4QgXyTYD0Ejr0u1zzdrqS60JvCcnIJezKSZ7dfh2yITgaayf3CCcQvKTJGkw2YLMOK3hIUBHIFS/bi5CHRSyzrlOoqk4fFyXogKN3LjrlqdaqoXWGTeq3P4a/6pSlEf40zeMNImY1nCFk+sauHUMMD6EOp0Ihgra+N+kghfrc6IeesiI/PqI4WmEObsyekdzF1TGFU/Aunl0u97W7rkTULKn/f3GCLHhuf5pXbIg/nj3U6sI/3C6wfOxPZqCi+FL+SOmKECdp9pLRRQ9RcYfSOTKEu7NMmpqOd1Og9KzbBnVtM4EMgQyprYKnfqZq1heRwjwfpuhxGR67sZ6CpM6bdLbdu7eui5L29ZjA=

