hugo:
  image: vimagick/hugo-arm
  command: >
    server --bind=0.0.0.0
           --port=80
           --baseUrl=http://blog.datageek.info/
           --watch
  ports:
    - "80:80"
  volumes:
    - ./www:/www
  restart: always
