apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  containers:
  - name: fluentd-elasticsearch
    image: feisky/fluentd-elasticsearch
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log

