InfluxSrv:
  image: 'tutum/influxdb:0.8.8'
  environment:
    - PRE_CREATE_DB=cadvisor
  expose:
    - '8090'
    - '8099'
  ports:
    - '8083:8083'
    - '8086:8086'
cadvisor:
  image: 'google/cadvisor:latest'
  command: '-storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086'
  links:
    - 'InfluxSrv:influxsrv'
  ports:
    - '8080:8080'
  volumes:
    - '/:/rootfs:ro'
    - '/var/run:/var/run'
    - '/sys:/sys:ro'
    - '/var/lib/docker:/var/lib/docker:ro'
grafana:
  image: 'grafana/grafana:2.0.2'
  environment:
    - INFLUXDB_HOST=localhost
    - INFLUXDB_NAME=cadvisor
    - INFLUXDB_PASS=root
    - INFLUXDB_PORT=8086
    - INFLUXDB_USER=root
  links:
    - 'InfluxSrv:influxsrv'
  ports:
    - '3000:3000'

