server:
  image: vimagick/fteproxy
  ports:
    - "80"
  environment:
    - "MODE=server"
    - "SERVER_IP=0.0.0.0"
    - "SERVER_PORT=80"
    - "PROXY_IP=www.google.com"
    - "PROXY_PORT=80"

client:
  image: vimagick/fteproxy
  ports:
    - "9009:80"
  links:
    - server
  environment:
    - "MODE=client"
    - "SERVER_IP=server"
    - "SERVER_PORT=80"
    - "CLIENT_IP=0.0.0.0"
    - "CLIENT_PORT=80"
