etcd:
  image: gcr.io/google_containers/etcd:2.2.1
  container_name: etcd
  ports:
    - "4001"
  command: ['/usr/local/bin/etcd', '-advertise-client-urls=http://0.0.0.0:4001', '--listen-client-urls=http://0.0.0.0:4001', '--data-dir=/var/etcd/data']

apiserver:
  image: gcr.io/google_containers/hyperkube:v1.1.1
  container_name: apiserver
  ports:
    - "8080:8080"
  links:
    - etcd
  command: ["/hyperkube", "apiserver", "--service-cluster-ip-range=10.254.0.0/16", "--insecure-bind-address=0.0.0.0", "--cluster-name=kubernetes", "--etcd_servers=http://etcd:4001", "--v=2"]
  environment:
    - "affinity:container==*etcd*"

controller:
  image: gcr.io/google_containers/hyperkube:v1.1.1
  command: ["/hyperkube", "controller-manager", "--address=0.0.0.0", "--master=http://apiserver:8080", "--v=2"]
  links:
    - apiserver
  environment:
    - "affinity:container==*apiserver*"

scheduler:
  image: gcr.io/google_containers/hyperkube:v1.1.1
  command: ["/hyperkube", "scheduler", "--address=0.0.0.0", "--master=http://apiserver:8080", "--v=2"]
  links:
    - apiserver
  environment:
    - "affinity:container==*apiserver*"

kubelet:
  image: gcr.io/google_containers/hyperkube:v1.1.1
  ports:
    - "4194"
  links:
    - apiserver
  command: ['/hyperkube', 'kubelet', '--containerized' , '--api_servers=http://apiserver:8080', '--v=2', '--address=0.0.0.0', '--enable_server', '--config=/etc/kubernetes/manifests']
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /dev:/dev
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw
  privileged: true
  # A kubelet shouldn't run alongside another kubelet - One privileged kubelet per node
  environment:
    - "affinity:container!=*kubelet*"

proxy:
  image: gcr.io/google_containers/hyperkube:v1.1.1
  command: ['/hyperkube', 'proxy', '--master=http://apiserver:8080', '--v=2']
  privileged: true
  links:
    - apiserver
  # A proxy should run alongside another kubelet but not alongside another proxy
  environment:
    - "affinity:container==*kubelet*"
    - "affinity:container!=*proxy*"
