#!/bin/bash

############################################# Author(s)




############################################# Notes

# https://github.com/m039/XLIS


############################################# Script

## include common functions
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. ${DIR}/bash/scripts/cs-common.sh

. ${DIR}/bash/scripts/xbuild/dockercross_functions.sh

dockercross_get_images_list

# Unity 3D / WP8 / mobile & desktop builds
dockercross_install_base "${DOCKERCROSS_NAMESPACE}/windows-x64"
dockercross_install_base "${DOCKERCROSS_NAMESPACE}/windows-x86"

# Unity 3D / Linux / mobile & desktop builds
dockercross_install_base "${DOCKERCROSS_NAMESPACE}/linux-x86"
dockercross_install_base "${DOCKERCROSS_NAMESPACE}/linux-x64"

# Unity 3D / Android / arm based mobile devices / Native Plugins
dockercross_install_base "${DOCKERCROSS_NAMESPACE}/android-arm"

print_separator

