#!/bin/bash

############################################# Author(s)




############################################# Notes

# https://github.com/m039/XLIS


############################################# Script

## include common functions
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. ${DIR}/bash/scripts/cs-common.sh

. ${DIR}/bash/scripts/xbuild/dockercross_functions.sh

dockercross_get_images_list

dockercross_install_base "dockcross/windows-x64"
dockercross_install_base "dockcross/windows-x86"

# dockercross_deploy_all