#define TEST_ASSETS_PATH "_TEST_ASSETS_PATH_"

#define TEST_MAPCSS_PATH TEST_ASSETS_PATH "mapcss/"
#define TEST_MAPCSS_DEFAULT "../../../unity/demo/Assets/StreamingAssets/mapcss/default/index.mapcss"

#define TEST_OSM_PATH TEST_ASSETS_PATH "osm/"
#define TEST_JSON_FILE TEST_OSM_PATH "moscow.osm.json"
#define TEST_JSON_2_FILE TEST_OSM_PATH "berlin.osm.json"
#define TEST_PBF_FILE TEST_OSM_PATH "berlin.osm.pbf"
#define TEST_XML_FILE TEST_OSM_PATH "berlin.osm.xml"
#define TEST_OSM_DUMMY_FILE TEST_OSM_PATH "test.dummy.osm.xml"
#define TEST_OVERPASS_DUMMY_FILE TEST_OSM_PATH "test.dummy.overpass.xml"

#define TEST_SHAPE_ARTIFICIAL TEST_ASSETS_PATH "shape/artificial/"
#define TEST_SHAPE_POINT_FILE TEST_SHAPE_ARTIFICIAL "point"
#define TEST_SHAPE_LINE_FILE TEST_SHAPE_ARTIFICIAL "line"
#define TEST_SHAPE_POLY_FILE TEST_SHAPE_ARTIFICIAL "poly"
#define TEST_SHAPE_MULTIPOLY_FILE TEST_SHAPE_ARTIFICIAL "multipoly"

#define TEST_SHAPE_NE_110M TEST_ASSETS_PATH "shape/naturalearth/"
#define TEST_SHAPE_NE_110M_LAND TEST_SHAPE_NE_110M "ne_110m_land"
#define TEST_SHAPE_NE_110M_RIVERS TEST_SHAPE_NE_110M "ne_110m_rivers_lake_centerlines"
#define TEST_SHAPE_NE_110M_LAKES TEST_SHAPE_NE_110M "ne_110m_lakes"
#define TEST_SHAPE_NE_110M_ADMIN TEST_SHAPE_NE_110M "ne_110m_admin_0_scale_rank"
#define TEST_SHAPE_NE_110M_BORDERS TEST_SHAPE_NE_110M "ne_110m_admin_0_boundary_lines_land"
#define TEST_SHAPE_NE_110M_POPULATED_PLACES TEST_SHAPE_NE_110M "ne_110m_populated_places_simple"
